sonar.host.url=https://sonarcloud.io
sonar.projectKey=viernes
sonar.organization=davidelezg-lab
sonar.projectName=viernes
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.exe,**/*.dll,**/*.obj,**/*.o,**/.gdca,/*.gcno,/*.gcov
sonar.projectVersion=1.0
