sonar.host.url=https://sonarcloud.io
sonar.projectKey=viernes
sonar.organization=davidelezg-lab
sonar.projectName=viernes
sonar.sources=main.cpp
sonar.tests=test.cpp
sonar.cfamily.gcov.reportsPath=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.exe,**/*.dll,**/*.obj,**/*.o,**/.scannerwork/**,**/build-wrapper-dump.json
sonar.projectVersion=1.0
